### ISSUE TITLE
embedding in ingestionPipeline returns node with embedding:undefined

### ISSUE THREAD

**Issue by shakedbuk123** [run-llama/LlamaIndexTS#533] opened 2024-02-09 14:50 UTC
i am doing a pipe line for documents splitting, extraction and then embedding, only the first batch of nodes has the embedding, the rest has the embedding property but it is undefined and no error is thrown. the only workaround I found was looping over the nodes again and embedding the undefined ones.  

```
try{ 
const llamaPipeline = async(content) =>{
  
    let OpenEmbedllm = new OpenAIEmbedding({
      temperature: 0,
             
      apiKey: process.env.OPENAI_SECRET_KEY,
        model:'text-embedding-3-small',
          apiVersion:"2023-07-01-preview",
    
    
    
    })
  const resFromAnalyze = await client.query(SELECT overlap,chunk_size
  FROM public.${process.env.PG_DB_PREFIX}_prompts;)
     let pipeline = new IngestionPipeline({transformations:[
      // new RemoveSpecialCharacters(),
      new SimpleNodeParser({ chunkOverlap:200,
        chunkSize:20}),
        new KeywordExtractor({llm:azureOpenAillm}),
        OpenEmbedllm
     ]})
     const nodes = await pipeline.run({documents:[new Document({text:content})]})
     console.log(nodes)
      return nodes
  
    }catch(err){
      console.log(err)
  
    }
  }

```

**Comment by EmanuelCampos** [comment] 2024-02-09 15:05
@shakedbuk123 can you share which version are you running?

I did the same test and all nodes contains embeddings

```ts
import { OpenAIEmbedding, Document, IngestionPipeline, SimpleNodeParser } from "llamaindex";

import essay from "./essay";

async function main() {
  const openaiEmbedding = new OpenAIEmbedding();

  const documents = [
    new Document({
      text: essay,
    })
  ];
  
  const pipeline = new IngestionPipeline({
    transformations: [
      new SimpleNodeParser({ chunkOverlap: 15, chunkSize: 20 }),
      openaiEmbedding
    ]
  });

  const nodes = await pipeline.run({ documents });

  console.log(nodes);
}


main().then(() => {
  console.log("Done");
})
```

and you chunk overlap can't be bigger than your chunk overlapping

**Comment by shakedbuk123** [comment] 2024-02-11 12:48
hey sorry for the delay,  I am running the latest  llamaIndex ts version and changed the chunk_size to  200 and overlap to 20
and still, only the first few nodes are embedded,  i should mention, the number of the nodes that are getting embedded changes according to the size of the document. it always like the first 10%.

**Comment by EmanuelCampos** [comment] 2024-02-11 12:51
> hey sorry for the delay, I am running the latest llamaIndex ts version and changed the chunk_size to 200 and overlap to 20
> and still, only the first few nodes are embedded, i should mention, the number of the nodes that are getting embedded changes according to the size of the document. it always like the first 10%.

Can you share an repo with a reproducible example? would help a lot.

**Comment by lishing** [comment] 2024-02-17 05:36
hey there, i run into the same problem as shakebuk12 - embeddings become undefined after a few rounds

**Comment by shakedbuk123** [comment] 2024-02-17 09:20
never solved it, ended up re iterating  on the nodes and embed the undefined ones manually. lemme know if you get something

**Comment by lishing** [comment] 2024-02-18 03:15
thanks @shakedbuk123. to everyone - does this work conceptually? I thought embeddings are done in the perspective of the whole article, since the vectors are established in relation to the words within the article.

**Comment by EmanuelCampos** [comment] 2024-02-18 10:26
Hello guys, just to reiterate this issue is already solved on main, we will be pushing a release soon.

**Comment by EmanuelCampos** [comment] 2024-02-18 21:28
The 0.1.11 was released with the fixs, let us know how it goes :)

**Comment by shakedbuk123** [comment] 2024-02-19 08:17
hey Emanuel it works for me now! ty so much!

**Closed** 2024-02-19 08:17 UTC
