### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by riteshwaghela** [run-llama/LlamaIndexTS#865] opened 2024-05-21 18:18 UTC
Following the example given in https://ts.llamaindex.ai/getting_started/starter_tutorial/retrieval_augmented_generation

below deps installed:
   "llamaindex": "^0.3.12"
    "@types/node": "^20.12.12",
    "typescript": "^5.4.5"

When trying to run the example code using 
`npx tsx example.ts`

```
ReferenceError: self is not defined
    at ./node_modules/.pnpm/onnxruntime-web@1.14.0/node_modules/onnxruntime-web/dist/ort-web.min.js (/Users/AI-ML/llama/node_modules/llamaindex/dist/cjs/internal/deps/transformers/transformers.js:2437:11)
    at __webpack_require__ (/Users/AI-ML/llama/node_modules/llamaindex/dist/cjs/internal/deps/transformers/transformers.js:40906:43)
    at ./src/backends/onnx.js (/Users/AI-ML/llama/node_modules/llamaindex/dist/cjs/internal/deps/transformers/transformers.js:19468:81)
    at __webpack_require__ (/Users/AI-ML/llama/node_modules/llamaindex/dist/cjs/internal/deps/transformers/transformers.js:40906:43)
    at ./src/env.js (/Users/AI-ML/llama/node_modules/llamaindex/dist/cjs/internal/deps/transformers/transformers.js:19608:83)
    at __webpack_require__ (/Users/AI-ML/llama/node_modules/llamaindex/dist/cjs/internal/deps/transformers/transformers.js:40906:43)
    at ./src/utils/hub.js (/Users/AI-ML/llama/node_modules/llamaindex/dist/cjs/internal/deps/transformers/transformers.js:37863:73)
    at __webpack_require__ (/Users/AI-ML/llama/node_modules/llamaindex/dist/cjs/internal/deps/transformers/transformers.js:40906:43)
    at ./src/tokenizers.js (/Users/AI-ML/llama/node_modules/llamaindex/dist/cjs/internal/deps/transformers/transformers.js:31498:79)
    at __webpack_require__ (/Users/AI-ML/llama/node_modules/llamaindex/dist/cjs/internal/deps/transformers/transformers.js:40906:43)
    at ./src/pipelines.js (/Users/AI-ML/llama/node_modules/llamaindex/dist/cjs/internal/deps/transformers/transformers.js:26796:80)
    at __webpack_require__ (/Users/AI-ML/llama/node_modules/llamaindex/dist/cjs/internal/deps/transformers/transformers.js:40906:43)
    at ./src/transformers.js (/Users/AI-ML/llama/node_modules/llamaindex/dist/cjs/internal/deps/transformers/transformers.js:35984:79)
    at __webpack_require__ (/Users/AI-ML/llama/node_modules/llamaindex/dist/cjs/internal/deps/transformers/transformers.js:40906:43)
    at Object.<anonymous> (/Users/ritesh.waghela/AI-ML/llama/node_modules/llamaindex/dist/cjs/internal/deps/transformers/transformers.js:40975:36)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
```

 Node Version - 18.20.2

below is the tsconfig.json
```
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "esnext",
    "moduleResolution": "bundler",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "lib": ["ES2022"],
    "types": ["node"],
    "outDir": "./lib",
    "tsBuildInfoFile": "./lib/.tsbuildinfo",
    "incremental": true,
    "composite": true
  },
  "ts-node": {
    "files": true,
    "compilerOptions": {
      "module": "commonjs"
    }
  },
  "include": ["./**/*.ts"]
}
```

**Comment by marcusschiesser** [comment] 2024-05-22 13:29
@riteshwaghela couldn't reproduce your problem on my macOS 14 machine using Node 18.20.1.  I tried `npm` and `pnpm`. As it happens in `onnxruntime-web@1.14.0` - maybe it's related to your system? What are you running under?

**Comment by riteshwaghela** [comment] 2024-05-22 16:10
My Environment

MacOs Sonoma - 14.14.1
Runtime - Node 18.20.2

**Comment by marcusschiesser** [comment] 2024-05-23 09:38
@riteshwaghela yes that seems to be the issue - it should not use onnxruntime-web but onnxruntime-node, seems to be related to https://github.com/xenova/transformers.js/issues/19#issuecomment-1472954178 - my guess is that I don't run into this condition using my tsx (version 4.9.4).

Can you please try the following things:
1. use the workaround from the comment above, adding to the beginning:
```
// https://github.com/microsoft/onnxruntime/issues/13072
global.self = global;
```
2. add tsx@4.9.4 to your dev dependencies and use `pnpm tsx example.ts` instead of `pnpx tsx example.ts`

**Comment by riteshwaghela** [comment] 2024-05-23 18:54
The error went away after using  

`(global as any).self = global;`

But got another error this time:


```
TypeError: pipeline is not a function
    at HuggingFaceEmbedding.getExtractor (/Users/ritesh.waghela/AI-ML/llama/node_modules/llamaindex/dist/cjs/embeddings/HuggingFaceEmbedding.js:37:36)
    at async HuggingFaceEmbedding.getTextEmbedding (/Users/ritesh.waghela/AI-ML/llama/node_modules/llamaindex/dist/cjs/embeddings/HuggingFaceEmbedding.js:44:27)
    at async HuggingFaceEmbedding.getTextEmbeddings (/Users/ritesh.waghela/AI-ML/llama/node_modules/llamaindex/dist/cjs/embeddings/types.js:33:31)
    at async batchEmbeddings (/Users/ritesh.waghela/AI-ML/llama/node_modules/llamaindex/dist/cjs/embeddings/types.js:61:32)
    at async HuggingFaceEmbedding.getTextEmbeddingsBatch (/Users/ritesh.waghela/AI-ML/llama/node_modules/llamaindex/dist/cjs/embeddings/types.js:43:16)
    at async HuggingFaceEmbedding.transform (/Users/ritesh.waghela/AI-ML/llama/node_modules/llamaindex/dist/cjs/embeddings/types.js:47:28)
    at async VectorStoreIndex.getNodeEmbeddingResults (/Users/ritesh.waghela/AI-ML/llama/node_modules/llamaindex/dist/cjs/indices/vectorStore/index.js:488:9)
    at async VectorStoreIndex.insertNodes (/Users/ritesh.waghela/AI-ML/llama/node_modules/llamaindex/dist/cjs/indices/vectorStore/index.js:578:17)
    at async VectorStoreIndex.buildIndexFromNodes (/Users/ritesh.waghela/AI-ML/llama/node_modules/llamaindex/dist/cjs/indices/vectorStore/index.js:498:9)
    at async VectorStoreIndex.init (/Users/ritesh.waghela/AI-ML/llama/node_modules/llamaindex/dist/cjs/indices/vectorStore/index.js:446:13)
    at async VectorStoreIndex.fromDocuments (/Users/ritesh.waghela/AI-ML/llama/node_modules/llamaindex/dist/cjs/indices/vectorStore/index.js:524:16)
    at main (/Users/ritesh.waghela/AI-ML/llama/example.ts:34:17)
```

**Comment by marcusschiesser** [comment] 2024-05-24 09:41
`HuggingFaceEmbedding` is actually using transformers.js - did you try `tsx@4.9.4` without `(global as any).self = global`?

**Comment by himself65** [comment] 2024-06-04 17:17
could you please upgrade llamaindex to latest?

**Comment by himself65** [comment] 2024-06-11 20:01
It has been fixed in the latest version

**Closed by himself65** 2024-06-11 20:01 UTC
Labels: bug
