### ISSUE TITLE
local llm loading issues

### ISSUE THREAD

**Issue by khalilxg** [run-llama/LlamaIndexTS#293] opened 2023-12-23 20:04 UTC
It seems there's trouble issues using local llms, if ussing llamacpp loading itll be no response from the model+no errors.

when itll be support for local llms, thank you !!

**Comment by himself65** [comment] 2024-01-02 22:41
Could you please give a minimum code to reproduce?

**Comment by himself65** [comment] 2024-01-03 01:43
We have ollama support which is a local LLM provider. You can have a try once it release

https://github.com/run-llama/LlamaIndexTS/pull/305

**Comment by hiepxanh** [comment] 2024-01-24 03:29
@khalilxg  using Ollama llama.cpp and any llm localhost which using OpenAI method and do this:

```
const modelUrl = "http://127.0.0.1:8080/v1";
const embeddingUrl = "http://127.0.0.1:9090";

 const serviceContext = serviceContextFromDefaults({
        llm: new OpenAI({
            additionalSessionOptions: {
                baseURL: modelUrl,
        } }),
        embedModel: new OpenAIEmbedding({
            additionalSessionOptions: {
                baseURL: embeddingUrl
        } }),
    });
    


```


    The document not say anything about this, it take me 3 hours to read though source code  haha

**Comment by himself65** [comment] 2024-01-24 03:42
> @khalilxg using Ollama llama.cpp and any llm localhost which using OpenAI method and do this:
> 
> ```
> const modelUrl = "http://127.0.0.1:8080/v1";
> const embeddingUrl = "http://127.0.0.1:9090";
> 
>  const serviceContext = serviceContextFromDefaults({
>         llm: new OpenAI({
>             additionalSessionOptions: {
>                 baseURL: modelUrl,
>         } }),
>         embedModel: new OpenAIEmbedding({
>             additionalSessionOptions: {
>                 baseURL: embeddingUrl
>         } }),
>     });
>     
> ```
> 
> The document not say anything about this, it take me 3 hours to read though source code haha

Oh great, thanks for doing this. We will update the doc later

**Comment by hiepxanh** [comment] 2024-01-24 06:44
@himself65 thank you so much, do you think can we create an shortcut like: baseUrl to pass as property like openAIkey?

**Comment by hiepxanh** [comment] 2024-01-26 03:00
@himself65  i do it myself 😄

**Comment by marcusschiesser** [comment] 2024-01-26 04:10
@hiepxanh Thanks a lot for your PR - why didn't you use the `Ollama` class: https://github.com/run-llama/LlamaIndexTS/blob/main/examples/ollama.ts ? Did you run in any problem using it?

**Comment by hiepxanh** [comment] 2024-01-26 05:46
Oh, I use llama.cpp and tried bout 10 like caddle, kolboldcpp, transformer.js .... too much thing, each one using different baseUrl and all follow openAI standards. At the first time, because I am following openAI tutorial, so I prefer custom u of this option. 

Ollama
Seem weird to me because it not in tutorial haha

**Comment by peterhirn** [comment] 2024-02-06 10:24
The `Ollama` class and examples mentioned above worked ootb for me, but I can't get the example from the readme to work (read `abramov.txt` and ask a question about the author) using only the local model without `OPENAI_API_KEY`.

I unsuccessfully tried
```ts
  const serviceContext = serviceContextFromDefaults({
    llm,
    embedModel: new OpenAIEmbedding({
      additionalSessionOptions: {
        baseURL: "http://127.0.0.1:11434/api/embeddings",
      },
    }),
  });

  const index = await VectorStoreIndex.fromDocuments([document], {
    serviceContext,
    logProgress: true,
  });
```

Am I doing it wrong?

**Comment by marcusschiesser** [comment] 2024-02-07 05:25
I think there are two problems here:

1. The confusion here is that the `Ollama` class implements an embedding model and an LLM, so this should work:

```
const llm = new Ollama({ model: "llama2", temperature: 0.5 });

  const serviceContext = serviceContextFromDefaults({
    llm,
    embedModel: llm
  });

  const index = await VectorStoreIndex.fromDocuments([document], {
    serviceContext,
    logProgress: true,
  });
```

@himself65, how about adding `OllamaEmbedding` as a type alias?

2. Using `OpenAI` and `OpenAIEmbedding` both require an `apiKey`, and if it is not provided, it tries to get it from the environment (i.e. `OPENAI_KEY`) 

@himself65, how about the following:

a. allowing directly setting the `baseURL` in the init params:

```
const modelUrl = "http://127.0.0.1:8080/v1";
const embeddingUrl = "http://127.0.0.1:9090";

 const serviceContext = serviceContextFromDefaults({
        llm: new OpenAI({
                baseURL: modelUrl,
        } }),
        embedModel: new OpenAIEmbedding({
                baseURL: embeddingUrl
        }),
    });
```

b. and if `baseURL` is set, we don't require an `apiKey`

**Comment by EmanuelCampos** [comment] 2024-02-12 15:56
Looks to be solved, closing the PR

Feel free to open again if needed

**Closed by EmanuelCampos** 2024-02-12 15:56 UTC
